cluster:
  name: test-cluster
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    auth:
      type: basic
      username: "2448345"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-028.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "1219849"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==
  - name: grafana-cloud-traces
    type: otlp
    url: https://tempo-prod-19-prod-ap-south-1.grafana.net:443
    protocol: grpc
    auth:
      type: basic
      username: "1214160"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: test-cluster
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom
  kepler:
    enabled: true
annotationAutodiscovery:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  connectors:
    grafanaCloudMetrics:
      enabled: true
alloy-metrics:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: test-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-018.grafana.net
    auth:
      type: basic
      username: "1262055"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==
alloy-singleton:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: test-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-018.grafana.net
    auth:
      type: basic
      username: "1262055"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==
alloy-logs:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-logs-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: test-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-018.grafana.net
    auth:
      type: basic
      username: "1262055"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: test-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-018.grafana.net
    auth:
      type: basic
      username: "1262055"
      password: glc_eyJvIjoiMTQzMzg1NCIsIm4iOiJzdGFjay0xMjYyMDU1LWludGVncmF0aW9uLWJyYW5kLXRva2VuLWJyYW5kLXRva2VuIiwiayI6Imd1eDhyMHA1VTdEMVk2SVBoOEk0MDB3SCIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==